// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-XlyociyQ_viz-KIpL03Q9dIkxW_muQ',
    appId: '1:963187662813:web:1c9fb16c1293309ff9a034',
    messagingSenderId: '963187662813',
    projectId: 'crud-151fd',
    authDomain: 'crud-151fd.firebaseapp.com',
    storageBucket: 'crud-151fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwL-rls7TpC8NQRGdwhX_88AbO12uKFA',
    appId: '1:963187662813:android:db0996a19358f809f9a034',
    messagingSenderId: '963187662813',
    projectId: 'crud-151fd',
    storageBucket: 'crud-151fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFd-wMl2mCAlMapY6j6HrqQ-k7OdfVLE',
    appId: '1:963187662813:ios:3fd71415f9902a49f9a034',
    messagingSenderId: '963187662813',
    projectId: 'crud-151fd',
    storageBucket: 'crud-151fd.appspot.com',
    iosClientId: '963187662813-krndpe02p9kmqatirgrranljl50folg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
